# Generated by Django 2.2 on 2020-02-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20200219_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='formatted_time',
            field=models.TextField(default='99'),
        ),
    ]
